### PR TITLE
SVC-3661: Create puppet module for lustre client install and configur…

### PR DESCRIPTION
**Pull request by billglick**
…ation

Add lustre fs type, module class
Add execs to module class
Add template file for modprobe.d/lustre.conf
Add lnet service

This is currently being tested in Ngale by @jakerundall 

We probably are not quite ready to merge this to main, but I'd like to start the review process in case we want to make changes to how this is done.

See:
- https://jira.ncsa.illinois.edu/browse/SVC-3661
- https://jira.ncsa.illinois.edu/browse/ASDPLNG-223

### CODE REVIEW

**Comment by jakerundall** [comment]
The code looks good to me so far. And I've retested against 83607f5 and it works fine.

I think we'll want to add iptables (ports can default to 988) from one or more CIDR ranges.

We may need to adjust dependencies for the lnet service depending on feedback from SVC-3661.

**Comment by jakerundall** [comment]
Suggest we change lnet service defaults to disabled/stopped (i.e., both params set to false). (But leave the capability in case we'd like also use this profile to configure LNet routers, which I think would be a good idea. Might be more development needed to handle the complete LNet router config?)

I actually originally tested on Ngale w/ these overridden to false and it seemed like it worked fine.

**Comment by billglick** [comment]
@jakerundall I've made your recommended changes. Can you review and retest this?

**Comment by jakerundall** [comment]
We'll need a couple of changes:
* init.pp should include the firewall sub-class
* firewall.pp should declare dports as Array[Integer] to match what will be in Hiera and what the dport param of the firewall resource is expecting to receive

I would also suggest not including the interface in the iptables rules. In theory we have to know and specify the interface names because of the the Lustre config anyway, but in general I think we're trying to move away from the extra overhead of specifying interface names. When we're specifying the source IP/range it doesn't add much security. We can always leave it in for now and discuss more, however. It's an easy enough update down the line.

**Comment by billglick** [comment]
I had added the `iniface` parameter to the `firewall` since we are already specifying the interface in hiera for `module` subclass. My original intent was to look up the interface from `profile_lustre_client::module::interface_name` and use that in the `firewall` class (without specifying it again specific to `firewall`). But then I chickened out about doing that, thinking it may be more obvious if it is an included parameter for `profile_lustre_client::firewall` directly.

I'm fine with any of the following options:
1. Remove the `iniface` parameter from the firewall rule entirely.
2. Move `profile_lustre_client::module::interface_name` to be simply `profile_lustre_client::interface_name` and look it up within both the `profile_lustre_client::module` & `profile_lustre_client::firewall` classes.
3. Or leave things **"as is"**.

Recommendations?

**Comment by jakerundall** [comment]
Gotcha, I'd say let's go with #2.

(I think when we tackle LNet routers we'll need to track a 2nd interface as well, but we can have a different param name and make dual-use of it for firewall and lnet config.)

**Comment by billglick** [comment]
I have moved both of the following parameters to the main class to make it more obvious that either of those could be referenced in any class:
```
$profile_lustre_client::interface_name
$profile_lustre_client::network_identifier
```

Then in subclasses `firewall` & `module` those are being assigned via a `lookup`.

`network_identifier` is currently only referenced in the `module` subclass, but eventually I think we may want it referenced elsewhere (e.g. `mounts`). Eventually we may want to do the same approach with an `$lnet_servers` array that is used for both `firewall` and `mounts`, and other future additions.

**Comment by jakerundall** [comment]
All works great, thanks!

**Review by jakerundall — APPROVED** [review]

**Pull request merged**
